FROM nginx:latest

COPY ./nginx.conf /etc/nginx/conf.d/default.conf
COPY ./web/static /var/www/Velik/static
COPY ./web/media /var/www/Velik/media

RUN chmod -R 755 /var/www/Velik/static
RUN chmod -R 755 /var/www/Velik/media

RUN chown -R www-data:www-data /var/www/Velik/static
RUN chown -R www-data:www-data /var/www/Velik/media

EXPOSE 80