services:
  web:
    build: ./web
    restart: always
    command: gunicorn --bind 0.0.0.0:8000 velik.wsgi:application

      # Раскомментируйте, если хотите применить миграции
      # ----------------------------------------------------------
      # python3 manage.py makemigrations;
      # python3 manage.py migrate
      # ----------------------------------------------------------

    depends_on:
      - db
    networks:
      - backend
      - server

  nginx:
    build: 
      context: .
      dockerfile: Dockerfile.nginx
    restart: always
    ports:
      - '80:80'
    depends_on:
      - web
      - db
    networks:
      - server

  api:
    build: ./api
    restart: always
    command: uvicorn main:app --host 0.0.0.0 --port 8080
    ports:
      - '8080:8080'
    depends_on:
      - db
    networks:
      - backend

  db:
    build: ./db
    ports:
      - '3306:3306'
    restart: always
    volumes:
      - velik_db:/var/lib/mysql

    networks:
      - backend

networks:
  backend:
  server:

volumes:
  velik_db: