# Generated by Django 5.1.4 on 2025-04-01 05:19

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("catalog", "0002_bikefavourites"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="bikemodel",
            name="star",
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name="bikemodel",
            name="star_count",
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name="bikefavourites",
            name="bike",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="bike_favorite",
                to="catalog.bikemodel",
            ),
        ),
        migrations.AlterField(
            model_name="bikefavourites",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="user_favorite",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.CreateModel(
            name="BikeStars",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("star", models.FloatField()),
                (
                    "bike",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="bike_star",
                        to="catalog.bikemodel",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="user_star",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
